# action.yml
name: 'Report test code coverage'
description: 'Report test code coverage to your deepsource repository'
inputs:
  DEEPSOURCE_DSN:  # id of input
    description: 'Deepsource DSN'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.DEEPSOURCE_DSN }}
